# Generated by Django 5.2.4 on 2025-08-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "dishes",
                    models.ManyToManyField(
                        blank=True, related_name="ingredients", to="kitchen.dish"
                    ),
                ),
            ],
        ),
    ]
