# Generated by Django 5.2.4 on 2025-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_ingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="dishes",
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="kitchen.ingredient"
            ),
        ),
    ]
